#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "blog: missing argument" >&2
    echo -ne "usage:\n\tblog [run|build]\n" >&2
    exit 1
fi

case "$1" in
"run"|"serve")
    bundle exec jekyll serve --incremental 
    ;;

"build")
    JEKYLL_ENV=production bundle exec jekyll build
    ;;

"publish")
    echo "building with prod settings..."
    JEKYLL_ENV=production bundle exec jekyll build
    BLOG_DIR=$(dirname "$0")
    pushd "$BLOG_DIR"
    COMMIT_MESSAGE=$(git log -1 --pretty=%B)
    pushd "$BLOG_DIR/_site"
    git add -A
    git commit -m "$COMMIT_MESSAGE"
    git push origin master
    popd; popd
    echo "published"
    ;;

*)
    echo "blog: unknown option: $1" >&2
    exit 2
    ;;
esac

