#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "blog: missing argument" >&2
    echo -ne "usage:\n\tblog [run|build]\n" >&2
    exit 1
fi

case "$1" in
"run")
    bundle exec jekyll serve --incremental 
    ;;

"build")
    bundle exec jekyll build
    ;;

*)
    echo "blog: unknown option: $1" >&2
    exit 2
    ;;
esac

